language: ruby
rvm:
  - 1.9.3
env:
  - RAILS_ENV=travis
before_script:
  - mysql -e 'create database statusbot_test;'
script:
  - bundle exec statusbot-models db:migrate
  - CODECLIMATE_REPO_TOKEN=97f8bd51229920d343c4275c0632abebff3815a309bf49beb3d85bf936c92609 bundle exec rake spec
